name: Test tweet
on:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - master
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Install dependecies
        run: |
          python setup.py install
          pip install tweepy

      - name: Tweet Stats
        continue-on-error: true
        env: #assign variables
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: |
          python tweet.py --name stats/Global/Weekly/stats --tweet 'OSM Last Week' --mention '@openstreetmap'
